version: 0.0
os: linux
files:
   - source: /
     destination: /home/ubuntu/Deploy/MS1
hooks:
   BeforeInstall:
    - location: start.sh
      runas: root
   AfterInstall:
    - location: stop.sh
      runas: root
